version: "3"

services:
  dev:
    image: ./dependencies.dockerfile
    working_dir: /work
    command: ./sbt run
    environment:
      PORT: 8080
      APP_NAME: scala-scratchpad-dev
    ports:
      - 8080:8080
    volumes:
      - .:/work
      - coursier-cache:/root/.cache/coursier
      - sbt-cache:/root/.sbt

volumes:
  coursier-cache:
    external: true
  sbt-cache:
    external: true
