steps:

#  - label: ":world_map: Validate TreasureMap"
#    plugins:
#      ssh://git@git.realestate.com.au/rea-systems/treasuremap-shovel-buildkite-plugin#0.0.3:
#        version: 1.0.88
#        validate: true
#        push: false

  - label: ":docker: Docker Freshness"
    branches: "!master"
    plugins:
      ssh://git@git.realestate.com.au/cowbell/docker-image-freshness-buildkite-plugin#v1:
        files: dependencies.dockerfile,docker-compose.yml,Dockerfile

  - label: ":stylelint: Scalafmt"
    command: ./auto/scalafmtCheckAll

  - label: ":sbt: Test"
    command: ./auto/test

  - block: ":handball: Deploy to Dev?"
    branches: "!master"

  - label: ":warning: DELETE THIS STEP AFTER THE INITIAL SEEDING - Seed Dependency Image"
    branches: master
    command: ./auto/seed-dependencies
    agents:
      queue: rea-artifacts:build
    plugins:
      - ssh://git@git.realestate.com.au/cowbell/ensure-ecr-buildkite-plugin#v1.0.3:
          namespace: property-insights
          repository: scala-scratchpad-dependencies
          regions: ap-southeast-2

  - label: ":1234: Generate Version"
    command: ./auto/generate-version
    plugins:
      - artifacts#v1.2.0:
          upload: target/version

  - label: ":sbt: Build Artifact"
    command: ./auto/build
    plugins:
      - artifacts#v1.2.0:
          upload: target/app.jar

  - wait

  - label: ":docker: Release"
    command: ./auto/release
    agents:
      queue: rea-artifacts:build
    plugins:
      - ssh://git@git.realestate.com.au/cowbell/ensure-ecr-buildkite-plugin#v1.0.3:
          namespace: property-insights
          repository: scala-scratchpad
          regions: ap-southeast-2
      - artifacts#v1.2.0:
          download:
            - target/app.jar
            - target/version
          upload: target/docker-image.txt

  - wait

  - label: ":ship: Deploy to Dev"
    command: ./auto/deploy-dev
    agents:
      queue: eventus-dev:deploy
    concurrency: 1
    concurrency_group: scala-scratchpad/deploy-dev
    plugins:
      - artifacts#v1.2.0:
          download: target/docker-image.txt

  - wait

  - label: ":llama: Deploy llama to Dev"
    command: ./auto/llama
    agents:
      queue: eventus-dev:deploy
    env:
      CONFIG_FILE: deploy/llama.yml
      CHECK_ID: dev

  - wait

  - label: ":rocket: Deploy to Prod"
    branches: master
    command: ./auto/deploy-prod
    agents:
      queue: eventus-prod:deploy
    concurrency: 1
    concurrency_group: scala-scratchpad/deploy-prod
    plugins:
      - artifacts#v1.2.0:
          download: target/docker-image.txt

  - wait

  - label: ":llama: Deploy llama to Prod"
    branches: master
    command: ./auto/llama
    agents:
      queue: eventus-prod:deploy
    env:
      CONFIG_FILE: deploy/llama.yml
      CHECK_ID: prod

  - wait

  - label: ":package: Publish Dependencies"
    branches: master
    command: ./auto/publish-dependencies
    agents:
      queue: rea-artifacts:build
    plugins:
      - ssh://git@git.realestate.com.au/cowbell/ensure-ecr-buildkite-plugin#v1.0.3:
          namespace: property-insights
          repository: scala-scratchpad-dependencies
          regions: ap-southeast-2

  # - label: ":world_map: Publish TreasureMap"
  #   branches: master
  #   plugins:
  #     ssh://git@git.realestate.com.au/rea-systems/treasuremap-shovel-buildkite-plugin#0.0.3:
  #       version: 1.0.88
  #       push: true

  # - label: ":green_book: Publish Docs"
  #   branches: master
  #   command: ./auto/doc-as-code
  #   agents:
  #     queue: skynet:doc-as-code
