#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

. deploy/config.sh

echo "INFO: Seeding dependencies image"

docker pull "639347700193.dkr.ecr.ap-southeast-2.amazonaws.com/property-insights/pi-http4s-api-stencil-test-dependencies:latest"

docker build \
  --cache-from "639347700193.dkr.ecr.ap-southeast-2.amazonaws.com/property-insights/pi-http4s-api-stencil-test-dependencies:latest" \
  --tag "$DEPENDENCIES_NAME" \
  --file dependencies.dockerfile \
  .

echo "INFO: Pushing $DEPENDENCIES_NAME to ECR"
docker push "$DEPENDENCIES_NAME:latest"
